// swift-tools-version:5.3

import PackageDescription

let package = Package(
    name: "Verovio",
    products: [
        .library(
            name: "Verovio",
            targets: ["Verovio"]
        ),
    ],
    targets: [
        .target(
            name: "Verovio",
            dependencies: [],
            path: ".",
            exclude: [
                "setup.py",
                "appveyor.yml",
                "MANIFEST.in",
                "COPYING.LESSER",
                "CHANGELOG.md",
                "codemeta.json",
                "Verovio.podspec",
                "COPYING",
                "README.md",
                "fonts/",
                "bindings/",
                "doc/",
                "emscripten/",
                "cmake/",
                "tools/",
                "Tests/",
                "include/json/LICENSE",
                "include/json/Makefile",
                "include/json/README.textile",
                "libmei/atts_fingering.cpp",
                "libmei/atts_usersymbols.cpp",
                "libmei/atts_harmony.cpp",
                "libmei/atts_performance.cpp",
                "libmei/atts_header.cpp",
                "libmei/atts_figtable.cpp",
                "libmei/atts_edittrans.cpp",
            ],
            sources: [
                "libmei/",
                "include/",
                "include/hum/",
                "include/json/",
                "include/midi/",
                "include/pugi/",
                "include/utf8/",
                "include/vrv/",
                "include/zip/",
                "src/",
                "src/hum/",
                "src/json/",
                "src/midi/",
                "src/pugi/",
            ],
            resources: [.copy("data/")],
            publicHeadersPath: "include",
            cxxSettings: [
                .headerSearchPath("libmei/"),
                .headerSearchPath("include/"),
                .headerSearchPath("include/hum/"),
                .headerSearchPath("include/json/"),
                .headerSearchPath("include/midi/"),
                .headerSearchPath("include/pugi/"),
                .headerSearchPath("include/utf8/"),
                .headerSearchPath("include/vrv/"),
                .headerSearchPath("include/zip/"),
                .headerSearchPath("src/"),
                .headerSearchPath("src/hum/"),
                .headerSearchPath("src/json/"),
                .headerSearchPath("src/midi/"),
                .headerSearchPath("src/pugi/"),
                .define("COCOAPODS"),
                .define("CLANG_CXX_LANGUAGE_STANDARD", to: "c++17"),
                .define("CLANG_CXX_LIBRARY", to: "libc++"),
                .define("GCC_C_LANGUAGE_STANDARD", to: "gnu11"),
                .define("GCC_DYNAMIC_NO_PIC", to: "NO"),
                .define("GCC_NO_COMMON_BLOCKS", to: "YES"),
                .define("GCC_SYMBOLS_PRIVATE_EXTERN", to: "NO"),
                .define("CLANG_ENABLE_OBJC_ARC", to: "YES"),
                .define("CLANG_ENABLE_OBJC_WEAK", to: "YES"),
                .define("ENABLE_STRICT_OBJC_MSGSEND", to: "YES"),
                .define("MTL_FAST_MATH", to: "YES"),
                .define("SUPPORTS_UIKITFORMAC", to: "NO"),
                .define("MTL_ENABLE_DEBUG_INFO", to: "NO"),
            ],
            linkerSettings: []
        ),
        .testTarget(name: "VerovioTests",
                    dependencies: ["Verovio"],
                    path: nil,
                    exclude: [],
                    sources: nil,
                    resources: nil,
                    cSettings: nil,
                    cxxSettings: [
                        .unsafeFlags(["-fmodules"]),
                        .unsafeFlags(["-fcxx-modules"])
                    ],
                    swiftSettings: nil,
                    linkerSettings: nil)
    ],
    cxxLanguageStandard: .cxx1z
)
